#9: add controller file and update application model and route
Younesnz/Volunet pull request #12
Opened 2023-07-09 16:14 UTC by sheidanouri

add controller file and update application model and route
the authentication needs to be added

2023-07-09 19:43 UTC, Younesnz requested changes

2023-07-09 19:43 UTC, Younesnz commented on src/controllers/applicationController.js
> +const Application = require('./applicationModel');
Shule jan, the relative path should be `../models/applicationModel`

2023-07-09 19:43 UTC, Younesnz commented on src/models/applicationModel.js
> +
please add @hapi/joi  validation for user inputs. it should return the validation function

2023-07-09 19:43 UTC, Younesnz commented on src/routes/applications.js
> +const auth = require('./auth');  // assuming you have an auth middleware to authenticate users
we'll add authentication functionality on the next tasks. for now focus on CRUD operations

2023-07-09 19:43 UTC, Younesnz commented on src/routes/applications.js
> +const applicationController = require('./applicationController');
the relative path should be `../controllers/applicationController`

2023-07-13 12:07 UTC, atakann approved these changes

2023-07-13 13:35 UTC, closed without merging