#9: add the readme file
Younesnz/Volunet pull request #28
Opened 2023-07-26 09:41 UTC by sheidanouri

added the readme file

2023-07-26 12:34 UTC, atakann requested changes
API endpoints that explains GET/PUT/DELETE methods with parameters should be added in a basic setting, responses can be added later.

Might be something like this:

GET /events

This endpoint returns a list of events filtered by user and #something#, and can be sorted by event date. It accepts the following query parameters:

    user: the user name to filter the events by
    #something#: a list of #something# names to filter the events by. Multiple events can be provided by separating them with commas

2023-07-27 01:20 UTC, abdulrahmanalbakkar approved these changes

2023-07-27 01:20 UTC, abdulrahmanalbakkar approved these changes

2023-07-28 05:50 UTC, atakann approved these changes

2023-07-28 14:47 UTC, merged